---
version: '3.7'
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 8989:8989
    volumes:
      - ./share/Container/container-station-data/persistent/sonarr/config:/config
      - ../share/Container/container-station-data/persistent/qbittorrent/downloads:/downloads
      - ./share/Multimedia/Video/Series:/tv
    links:
      - qbittorrent
      - jackett
  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 7878:7878
    volumes:
      - ./share/Container/container-station-data/persistent/radarr/config:/config
      - ./share/Container/container-station-data/persistent/qbittorrent/downloads:/downloads
      - ./share/Multimedia/Video/Films:/tv
    links:
      - qbittorrent
      - jackett
  jackett:
    image: linuxserver/jackett
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 9117:9117
    volumes:
      - ./share/Container/container-station-data/persistent/jackett/config:/config/Jackett
      - ./share/Container/container-station-data/persistent/jackett/api:/api
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8083
    ports:
      - 8083:8083
    volumes:
      - ./share/Container/container-station-data/persistent/qbittorrent/config:/config
      - ./share/Container/container-station-data/persistent/qbittorrent/downloads:/downloads
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./share/Container/container-station-data/persistent/heimdall/config:/config
    ports:
      - 9000:80
      - 443:443
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./share/Container/container-station-data/persistent/bazarr/config:/config
      - ./share/Multimedia/Video/Films:/movies
      - ./share/Multimedia/Video/Series:/tv
    ports:
