---
version: '3.7'
services: 
  sonarr:
    image: linuxserver/sonarr
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports: 
      - 8989:8989
    volumes:
      - <path/to/files/>:/config
      - <path/to/files/>:/tv 
      - <path/to/files/>:/downloads 
    links:
      - qbittorrent
      - jackett
  radarr: 
    image: linuxserver/radarr
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports: 
      - 7878:7878
    volumes:
      - <path/to/files/>:/config 
      - <path/to/files/>:/tv 
      - <path/to/files/>:/downloads 
    links:
      - qbittorrent
      - jackett
  jackett:
    image: linuxserver/jackett
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
    ports: 
      - 9117:9117
    volumes:
      - <path/to/files/>:/config/Jackett
      - <path/to/files/>:/api
  qbittorrent:
    image: linuxserver/qbittorrent
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam 
      - WEBUI_PORT=8083
    ports: 
      - 8083:8083
    volumes:
      - <path/to/files/>:/config
      - <path/to/files/>:/downloads


